name:                trajectory-algebra
version:             0.1.0.0
github:              "githubuser/trajectory-algebra"
license:             BSD3
author:              "Soufiane Maguerra"
maintainer:          "soufiane.maguerra@commercetools.com"
copyright:           "2020 Soufiane Maguerra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trajectory-algebra#readme>

dependencies:
- base >= 4.7 && < 5
- either
- refined
- singletons
- template-haskell

library:
  source-dirs: src

executables:
  trajectory-algebra-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trajectory-algebra

tests:
  trajectory-algebra-spec:
    main: Spec.hs
    source-dirs:
    - test/spec
    - test/common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trajectory-algebra
    - QuickCheck
    - quickcheck-classes
    - smallcheck
    - tasty
    - tasty-quickcheck
    - tasty-smallcheck
  trajectory-algebra-inference:
    main: Spec.hs
    source-dirs:
    - test/infer
    - test/common
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - trajectory-algebra
      - QuickCheck
      - quickspec
